services:
  clean-cut-mcp:
    build: .
    container_name: clean-cut-mcp
    ports:
      - "6970:6970"  # Remotion Studio (WORKING)
      - "6971:6971"  # Reserved for future HTTP MCP server
    volumes:
      # Cross-platform export directory mounting (WORKING - tested)
      # Videos exported from Remotion Studio appear in ./clean-cut-exports on your host
      - ./clean-cut-exports:/workspace/out
      # Persistent workspace - animations survive container rebuilds (NEW - host-mounted for transparency)
      - ./clean-cut-workspace:/workspace
    environment:
      - NODE_ENV=production
      - DOCKER_CONTAINER=true
      - REMOTION_STUDIO_PORT=6970
      - REMOTION_NON_INTERACTIVE=1
      - CHOKIDAR_USEPOLLING=true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6970/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

networks:
  default:
    name: clean-cut-mcp-network